version: '3.8'

services:
  fingpt-server:
    build: .
    container_name: fingpt_mf_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" # This maps the port from .env to your host
    dns:
      - 8.8.8.8
    env_file:
      - .env  # This injects the variables INSIDE the container
    volumes:
      - .:/app
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1